drashland/drash

example-app/resources/home_resource.ts
src/http/server.ts
src/services/http_service.ts
tests/unit/services/http_service_test.ts

Fix request url parsing

---

docs/public/assets/json/api_reference.json
docs/src/vue/components/global/page_api_reference_members_only.vue
docs/src/vue/components/pages/api-reference/util/exports.vue
docs/src/vue/components/sidebar.vue
src/compilers/doc_blocks_to_json.ts
src/util/members.ts

Issue #62 doc block parser matches more than expected

---

console/install_deno
deps.ts
mod.ts

https://github.com/denoland/deno/commit/525784e5642cbd869c682a0fda595f55c785d607

Upgrade deno to v0.29.0

---

deps.ts
mod.ts
src/exceptions/name_collision_exception.ts
src/http/server.ts
src/loggers/console_logger.ts
src/loggers/file_logger.ts
src/loggers/logger.ts
tests/members.ts
tests/test.ts
tests/unit/exceptions/name_collision_test.ts
tests/unit/loggers/console_logger_test.ts
tests/unit/mod_test.ts

https://github.com/drashland/deno-drash/issues/18

namespace loggers #18

---

deps.ts
mod.ts
src/compilers/doc_blocks_to_json.ts
src/core_loggers/console_logger.ts
src/core_loggers/file_logger.ts
src/core_loggers/logger.ts
src/http/resource.ts
src/http/response.ts
src/http/server.ts
src/interfaces/logger_configs.ts
src/services/http_request_service.ts
src/services/string_service.ts
src/util/members.ts

Updated all types where possible in the src/ dir

---

README.md
example_app/coffee_resource.ts
src/http/response.ts
tests/unit/http/server_test.ts

- Handles redirect to internal paths or external urls.
- Tests

request.redirect

---

src/http/server.ts

[issue-#164-root-favicon] serve favicon from root

---

mod.ts

[issue-#167-interface-types] export as types

---

example_app/cookie_resource_test.ts
tests/unit/http/middleware_test.ts

Fixed the cookie test leaking resources
Uncommted the middle ware test, seems to be no problem
tested all server tests, they seem to be  ok

Issue #157 leaking tests

---

example_app/app_server.ts
example_app/app_server_two.ts
example_app/app_test.ts
example_app/app_two_test.ts
example_app/cookie_resource_test.ts
example_app/request_accepts_resource.ts
example_app/request_accepts_resource_test.ts
example_app/request_accepts_two_resource.ts
example_app/request_accepts_two_resource_test.ts
example_app/template_engine_null_data_resource.ts
example_app/template_engine_null_data_resource_test.ts
example_app/template_engine_resource.ts
example_app/template_engine_resource_test.ts
example_app/view_resource.ts
example_app/view_resource_test.ts
src/services/http_request_service.ts

**Overview**
Also removed an old fixme that i had left in whilst i was writing the tests (the fixme was resolved in the leaking-tests issue)
* Added a new `accepts` method
* Tests written
* `api_reference.json` will be updated once this PR is closed and completed
* Wonder if other parts of the docs might need to be updated so developers would use this apporach instead?

Issue #173 accept content type

---

deps.ts
example_app/app.ts
example_app/app_https.ts
example_app/app_test.ts
example_app/app_two_test.ts
example_app/request_accepts_two_resource.ts
example_app/request_accepts_two_resource_test.ts
mod.ts
src/http/server.ts
tests/members.ts
tests/unit/http/middleware_test.ts
tests/unit/http/server_test.ts
tests/unit_minimal/server_test.ts

Issue #196 expose server.port

---

.github/pull_request_template.md

Thought it might be a good idea to have a PR template too. Not a problem if it isn't wanted or needed. If it's going to be added then feel free to suggest edits to make to the file to reflect Drash's workflow

Created PR template file

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/bug_report.md
README.md

Improved our `README.md` and added `CONTRIBUTING.md` for contributing guidelines.

Markdown improvements

---

example_app/app_1.ts
mod.ts
src/dictionaries/mime_db.ts
src/http/middleware.ts
src/http/server.ts
src/interfaces/server_configs.ts
tests/unit/decorators/middleware_test.ts

Fixes #214
Commits message answer this.

Middleware fix

---

src/http/server.ts
src/services/http_request_service.ts

Issue #223 handle invalid json

---

.github/CONTRIBUTING.md
.github/workflows/master.yml
console/create_app/app_api.ts
console/create_app/app_web_app.ts
console/create_app/config.ts
console/create_app/deps.ts
console/create_app/resources/home_resource.ts
console/create_app/resources/home_resource_api.ts
console/create_app/tests/resources/home_resource_test.ts
console/create_app/vue/app.js
console/create_app/webpack_vue.config.js
create_app.ts
deps.ts
src/http/server.ts
src/services/http_request_service.ts
tests/create_app_test.ts

Fixes #226 
Made workflow run `deno fmt-check` 
I haven't ran a `deno fmt`, hoping the build errors so we know everything works - then I will add a new commit for the format and test the build passes

Issue #226 improve workflow

---

.github/workflows/bumper.yml

Add `v` for deno version
set time to 00:45 utc to temporarily run it for testing purpsoes

Added v to deno version and made it run at 00:45am utc temporarily

---

.github/workflows/bumper.yml

* Use the master branch for dmm
* Fix permissions for running dmm (not sure on the correct usage for `=...` :S)

[ci] Fix bumper script

---

create_app.ts
tests/cli/create_app_test.ts

[issue-#254-add-logging-to-create-app-script] add logging

---

tests/unit/http/response_test.ts

Adds tests for #270 , fixed in https://github.com/drashland/deno-drash/pull/274

[issue-#270-encoding] Added extra tests

---

README.md

Added youtube badge to readme that links to the Drash playlist

[add-youtube-badge] Added youtube badge to readme

---

DEV.md
README.md
egg.json
mod.ts

Preps for drash v1.0.7
* Updates readme
* Updates `Drash.version`
* Updates `eggs.json`

[prep-for-release] Update eggs.json and drash version strings

---

create_app.ts
src/http/request.ts
tests/cli/create_app_test.ts

Address any doc blocks that are not uniformed, and do not follow Deno's standards

[uniform-docblocks] Uniform docblocks

---

src/http/resource.ts

Fixes #294 
* Removed the code and doc blocks related to this property on the resource class

[issue-#294-remove-resource-middleware-prop]

---

deps.ts
src/http/request.ts
src/interfaces/parsed_request_body.ts
tests/unit/http/request_test.ts

Fixes #277 
* Improved the interface for parsedBodyRequest to match it's actual expected data
* Due to this, a lot of types in the request class had to be changed, but as a bonus, there were no lint errors after making these changes

Issue #277 remove any in interface

---

.github/workflows/project.yml

Just moving my branch to be used under the org.

Project workflow

---

.github/CONTRIBUTING.md

Fixes [#<issue number>](url of issue)
n/a
Contribution href pointed to bad link
* Bullet points of developments made
point to new updated link
n/a
* Any other useful information goes here

Fix dead link

---

DEV.md

* Adds new instructions
* Removes old instructions
* Improves existing instructions

add more instructions

---

mod.ts
src/http/middleware.ts
src/http/response.ts
src/http/server.ts
src/interfaces/logger_configs.ts
src/interfaces/parsed_request_body.ts
src/interfaces/server_configs.ts
tests/members.ts
tests/unit/dictionaries/log_levels_test.ts
tests/unit/mod_test.ts

Partially address #283, but unable to crack one final `any`
* Initially took this on to address the middleware issue, but then decided to check the rest of the codebase and try improve where I could

Improve types

---

README.md
console/create_app/deps.ts
egg.json
mod.ts

Prepare to release drash v1.2.3

bump versions

---

.github/workflows/bumper.yml

* Fix bumper script as it failed when running
* Completely my fault 😕

[fix-bumper] fix bumper script

---

deps.ts
mod.ts
src/core_loggers/console_logger.ts
src/core_loggers/file_logger.ts
src/dictionaries/log_levels.ts
src/http/middleware.ts
src/http/resource.ts
src/http/server.ts
src/interfaces/parsed_request_body.ts
src/interfaces/resource.ts
src/interfaces/server_configs.ts
src/interfaces/server_middleware.ts
tests/members.ts

fix: Correct imports/exports to adjust to using --unstable

---

.github/workflows/bumper.yml
.github/workflows/master.yml
README.md
console/create_app/deps.ts
deps.ts
egg.json
mod.ts
tests/deps.ts

* Prepares to relese 1.2.4
* updates dependencies as well - thought may as well do it all in one PR

chore: bump versions and update dependencies

---

.github/workflows/bumper.yml
.github/workflows/master.yml
console/create_app/deps.ts
deps.ts
src/http/request.ts
src/http/response.ts
src/http/server.ts
tests/cli/create_app_test_http.ts
tests/cli/create_app_test_local.ts
tests/deps.ts
tests/members.ts
tests/unit/http/request_test.ts

This was auto-generated by GitHub Actions.

chore: Update dependencies

---

egg.json

[fix-egg-file-please] correct egg.json

---

console/create_app/package_react.json
console/create_app/public/views/index_react.html
console/create_app/react/app.tsx
console/create_app/tsconfig_react.json
console/create_app/webpack_react.config.js
create_app.ts
tests/cli/create_app_test_local.ts

Fixes #376 
* Bullet points of developments made
* Any other useful information goes here

feat: Add -with-react flag to create app

---

tests/cli/create_app_test_http.ts

Fixes [#<issue number>](url of issue)
* Bullet points of developments made
* Any other useful information goes here

chore: fix http create app tests

---

src/http/server.ts
tests/integration/app_3000_resources/optional_path_params_test.ts
tests/integration/app_3000_resources/resources/optional_path_params_resource.ts

Fixes #370 
* Removes hardcoded alphanumeric matching on first param which caused the regex to stop matching early on

fix: optional args regex not matching non-alphanumeric characters

---

.github/workflows/release.yml

* should hopefully send a reddit post and tweet on release

chore: Automate tweets and reddit on release

---

README.md

* missed including this when i did the with react flag for create app

chore: Include usage of react with create app section

---

.github/workflows/release.yml
egg.json

fix: Fix publishing to nest.land

---

.github/workflows/master.yml
README.md
console/bumper_ci_service.ts
console/bumper_ci_service_files.ts

* Uses latest deno version in workflows
* Cleans up bumper file following the above
* Remove duplication in README

chore: Remove bloat

---

src/http/response.ts
tests/unit/http/response_test.ts
tests/unit/http/server_test.ts

feat: support send binary body

---

src/http/request.ts

fix: getBodyFile only returning the first file is input is multiple

---

.github/release_drafter_config.yml

chore: Update release drafter

---

src/services/graphql/graphql.ts
tests/integration/graphql_test.ts

code formatting for graphql service

chore(graphql): code formatting

---

src/http/request.ts
src/services/graphql/deps.ts
src/services/graphql/graphql.ts
tests/deps.ts
tests/integration/graphql_test.ts

WIP. Ref: https://github.com/drashland/deno-drash-middleware/pull/118/files

feat: Graphql service

---

src/http/request.ts
src/http/server.ts
src/services/etag/deps.ts
src/services/etag/etag.ts
tests/deps.ts
tests/integration/etag_test.ts

feat: Add etag service

---

console/deps.ts
deps.ts
src/services/csrf/deps.ts
tests/deps.ts

chore(deps): bump to std@0.120.0

---

src/http/error_handler.ts
src/http/response.ts
src/services/graphql/graphql.ts
tests/deps.ts
tests/integration/error_handler_test.ts
tests/test_helpers.ts
tests/unit/http/response_test.ts

feat: Support specifying statu and extra headers in response body methods

---

src/http/response.ts
tests/unit/http/response_test.ts

partially addresses #599 
Leaving issue open as we need to figur eout how to test this

fix: Response.file not working with images

---

src/http/request.ts
src/http/response.ts
src/http/server.ts

closes #626 
@crookse ive tried checking everywhere, any places you think ive missed?

chore: Update docblocks

---

console/deps.ts
src/services/csrf/deps.ts
src/services/etag/deps.ts
src/services/graphql/deps.ts

Updates services' deps to latest Deno Standard Modules

chore: update services' deps

---

src/http/error_handler.ts
src/http/server.ts
src/interfaces.ts
tests/integration/error_handler_test.ts
tests/unit/http/error_handler_test.ts

feat: add connInfo to error handlers

---

src/services/tengine/jae.ts
tests/unit/services/jae_test.ts

feat: Check for tailing/leading slashes in Jae

---

src/services/csrf/deps.ts
src/services/etag/deps.ts

Bumps deps. Bumping services deps will be included in bumper's CI flow now.

chore(deps): bump deps for services

---

AUTHORS

Adding AUTHORS file to pull into the version branches

chore: add authors
