- .travis.yml
- README.md
- RELEASES.md
- console/install.deno
- deno_std.ts
- docs/webpack.config.js
- src/http/request.ts
- src/http/server.ts
- tests/members.ts
- tests/unit/http/server_test.ts
- Support deno v0.6.0 - latest
- Update tests
- Update CI
- Update installer
- Write Releases document showing compatibilities between Drash and Deno
> upgrade-deno

- src/http/server.ts
While testing deno-drash-docs, it was discovered that testing the Drash server object via `fetch()` wouldn't work unless `Drash.Http.Server.deno_server` was made public.
> [make-deno-server-public] make Drash.Http.Server.deno_server public

- README.md
As `server` is not meant to be mutated, it would be better to set it as a const.
> Fix lint in Readme.MD

- deps.ts
- example_app/app_server.ts
- example_app/app_test.ts
- example_app/cookie_resource.ts
- src/http/response.ts
- src/services/http_request_service.ts
Implements #143 
I will make a pr to deno-drash docs once this PR is approved in case someone wants me to adjust something which could lead to a doc block change.
**Developments**
Added the ability to get a cookie, set a cookie and delete a cookie. This functionality is about 95% Deno, utilising their cookie module. It conforms to the standards e.g. include `path`, `expiry` etc.
The get cookie function resides inside the request object, and will use Deno's `getCookies` to retrieve a single cookie, as there isn't an already built function to get a single one.
The delete cookie and set cookie functions reside inside the response class. The reason why these functions are re-defined is so it can allow type hints whilst writing the code as simply doing `public setCookie = setCookie` threw no …
> Added Cookie handling

- example_app/app_server.ts
- example_app/public/pretty/index.html
- src/http/response.ts
- src/http/server.ts
- src/interfaces/server_configs.ts
To test:
1. `cd example_app`
2. `deno --allow-all app.ts`
3. Go to `localhost:1447`
4. Go to `localhost:1447/public/pretty`
5. Go to `localhost:1447/public/pretty/index.html`
> [issue-#159-pretty-links] add pretty links

- deps.ts
- src/http/server.ts
Closes #199
Example usage:
```typescript
import { Drash } from "../deno-drash/mod.ts";
class HomeResource extends Drash.Http.Resource {
static paths = ["/"];
public GET() {
this.response.body = "Hello World!";
return this.response;
}
}
const server = new Drash.Http.Server({
response_output: "text/html",
resources: [HomeResource]
});
await server.run({
hostname: "localhost",
port: 1447
});
console.log("server running");
```
> allow await on server.run()

- DEV.md
- console/typescript/bump_versions.ts
- mod.ts
- tests/unit/mod_test.ts
Added a `version` property to the `Drash` namespace.
Also updated the `console/typescript/bump_versions` script to include the updating of the string in `mod.ts`
Example usage:
```typescript
import { Drash } from "https://deno.land/x/drash@v0.41.0/mod.ts";
console.log(Drash.version) // "v0.41.0"
```
> Added version property to Drash namespace

- src/http/server.ts
- tests/unit/mod_test.ts
This doesn't address any issue and only simplifies some functions. A *rationale* will be provided for each function.
- General
- Changed `let` to `const` anywhere it was possible as it recommended from most JS/TS guidelines.
- Changed string concatenations to string literals for better readability.
- `executeMiddlewareServerLevelBeforeRequest()` and `executeMiddlewareServerLevelAfterRequest()`
- Removed resource parameter from function signature since it's never used in middleware.
- Fixed all calls to the functions to account for new change.
- `handleHttpRequestForFavicon()`
- Removed empty `catch` statement since we can change the body based on it.
- `handleHttpRequestForStaticPathAsset()`
- Swapped deep multi level `if/else` statements to a single one with various exit points for …
> Server functions refactor

- mod.ts
- src/http/middleware.ts
- tsconfig.json
Removed the need for middleware decorators to have extra configs in `tsconfig.json`.
```typescript
// Before
@Drash.Http.ClassMiddleware({ before_request: [LogAfter] })
class HomeResource extends Drash.Http.Resource {
static paths = ["/"];
@Drash.Http.MethodMiddleware({ before_request: [LogAfter] })
public GET() {
return this.response;
}
}
```
```typescript
// After
@Drash.Http.Middleware({ before_request: [LogAfter] })
class HomeResource extends Drash.Http.Resource {
static paths = ["/"];
@Drash.Http.Middleware({ before_request: [LogAfter] })
public GET() {
return this.response;
}
}
```
Before we could use that standalone `Middleware()` signature, but it required some horrible `tsconfig.json` like [this](https://github.com/drashland/deno-drash/pull/186#issuecomment-617353887).
The …
> Improved middleware API

- DEV.md
- README.md
- REQUIREMENTS.md
- console/install_deno
- console/typescript/bump_versions.ts
- deps.ts
- mod.ts
- tests/unit/mod_test.ts
Upgrades deno to v1.0.1 from v1.0.0 (std 0.50.0)
* Updated all references to deno's and drash's version to reflect the new one
* Any other useful information goes here
> upgrade deno to v1.0.1

- README.md
- REQUIREMENTS.md
- console/install_deno
- console/tests
- console/typescript/bump_versions.ts
- deps.ts
- mod.ts
- tests/unit/mod_test.ts
This PR removes the integration tests. This PR has the v1.0.4 tag as well. When this merges into master, I will push the v1.0.5 tag.
> Upgrade deno to v1.0.5

- .github/workflows/bumper.yml
CI uses hard coded values to see if its a problem with the environmental variables. Also echos out that vars to see if they are defined in the current context
> [fix-bumper-ci] Using hard coded version values

- .github/workflows/bumper.yml
Tested and this works. If you would rather have the versions as environmental variables then we would need investigate why they it isn't working. Oddly, if you add a new run block, and echo the vars - they show correctly. But it works at the moment and it doesn't come off as bad practice (but env vars would be ideal of course)
I'm fine with either way
> Fix bumper ci

- create_app.ts
Hi, 
When you display the options of create-app.ts with : `deno run --allow-run --allow-read https://deno.land/x/drash@v1.0.5/create_app.ts --help` as suggested in [deno official website doc](https://deno.land/x/drash/#create-drash-app), example usage in output is incorrect : 
There is a permission missing in the last command in order to scaffold an app.
> Missing permission in create_app.ts help message example

- .github/workflows/master.yml
- create_app.ts
- tests/cli/create_app_test.ts
Fixes #232 
* Added assertions for stdout and stderr
* Removed one test because it isn't actually needed and covered by the test that requires a main argument (a main argument is either: --help, --api or --web-app and not --with-vue)
> Issue #232 improve create app tests

- mod.ts
- src/http/server.ts
- src/interfaces/server_middleware.ts
Fixes #276 
* Moved type for middleware into it's own file
* Server#middleware now uses the interface
* Added the interface to `Drash.Interfaces`
> Add server middleware interface

- .gitignore
- src/http/request.ts
- tests/members.ts
- tests/unit/http/request_test.ts
Intent on re-adding commented out tests, denoted by `// TODO`. Still unable to address the one left left, but provided information for when it is looked into again
> Address todo tests

- src/http/request.ts
- tests/integration/app_3000_resources/files_resource_test.ts
- tests/integration/app_3000_resources/resources/files_resource.ts
- tests/unit/http/request_test.ts
Fixes #269 
* Notes are seen in the issue, but I have corrected the logic for getting data. `getBodyFile` was using `.value` when it should be using `.file`. Also adjusted the return type.
* `getBodyParam` wasn't accounting for a parsed body request as multipart/form-data, so I have added extra logic to account for that.
* Re-added tests for these fixes
> Issue #269 get formdata body

- mod.ts
- src/http/request.ts
- src/http/response.ts
- src/http/server.ts
- src/services/http_service.ts
- src/services/string_service.ts
- tests/unit/http/request_test.ts
No issue for this. I was converting Sockets to use TSDoc and decided to check Drash's doc block formatting and the `@return` vs `@returns` annotations.
> [tsdoc-cleanup] clean up tsdoc docblocks

- README.md
Adds a section "What Makes Drash Different" to the README, to further differentiate ourselves from other frameworks as I believe it's key to do so
> [update-readme] add What Makes Drash Different section

- src/http/response.ts
- src/http/server.ts
- tests/unit/http/middleware_test.ts
- tests/unit/http/response_test.ts
Closes #324 
* This PR removes logic that makes `response.sendStatic()` read files. The caller is now in charge of reading files, setting `response.body` and then calling `sendStatic()`. `sendStatic()` takes 0 arguments now.
* This PR allows middleware to execute before and after HTTP requests to static assets
> Issue #324 execute middleware for static assets

- .github/workflows/master.yml
- create_app.ts
- tests/cli/create_app_test_http.ts
- tests/cli/create_app_test_local.ts
Fixes #350 
* When used as follows, it should fetch the contents from URLs and not try to read from folders it doesn't know about:
```
deno run --allow-read --allow-run --allow-write --allow-net https://deno.land/x/drash@v1.x/create_app.ts
```
* The issue was that `Deno.readFileSync()` was trying to do `Deno.readFileSync("http://deno.land/x/...")`. Instead, it should've been `await fetch("http://deno.land/x/...");`.
* The `create_app_test_http.ts` will fail because it's doesn't yet have the fix. It's fetching drash v1.x, but currently, drash v1.x doesn't have the fix. I can make the tests pass, but I'd have to change the branch name in the tests from v1.x to create-app-script-caching. Also, every time we update this script now (in regards to the HTTP …
> create app script fetching

- .github/workflows/release.yml
- egg.json
Fixes [#<issue number>](url of issue)
* Tonn of errors when the publish ci ran for 1.2.4, fixed by upgrading
* due to upgrading, the `egg.json` file needed updating too (new fields)
* on top of this, i added `checkAll: false` because the testing eggs did failed, and i don't think we should write out our whole testing commands in that one line - plus, it's already tested
> chore: fix publish CI

- src/http/request.ts
- tests/integration/app_3000_resources/resources/coffee_resource.ts
- tests/unit/http/request_test.ts
Fixes #384 and #378
* Passing in a body param that is false will not return null, and instead return it's expected value
* Assume that a body param can be of any type and not just a string
> fix: Dont return null if body param is false; Support body params being data types other than a string

- .github/workflows/release.yml
* On releasing, send a github event to the website repo so it can automate the process of updating the drash versions
> chore: Send request to website on release to update versions

- src/http/response.ts
* Found as part of getting cors middleware to work. Content length on response was 2 even when body was empty. This is because (see code changes), when `this.body` is empty, and you try `JSON.stringify` it, the result will be:
```
console.log(JSON.stringify("")) // """"
```
It essentially adds data and thus a body. So the body is **actually** empty, but when it comes to encoding that, it's a Uint8Array with a length of four, because we are pretty much doing `new TextEncoder().encode('""')`, which is wrong
> fix: Content length was 2 when content type is JSON and body is empty

- .github/workflows/master.yml
- src/http/request.ts
- tests/cli/create_app_test_http.ts
- tests/unit/http/request_test.ts
- tsconfig.json
Fixes [#382]
getAllUrlQueryParams takes as input url query params and returns a record whose keys are the query params and whose values are the corresponding values of the query params. If no params are given, then null is returned. 
The jsdoc documentation for getAllUrlQueryParams probably could be worded a little better.
> feat: Add getAllUrlQueryParams method

- src/http/server.ts
- tests/integration/app_3000_resources/resources/returning_invalid_response_in_resource.ts
- tests/integration/app_3000_resources/returning_invalid_response_in_resource_test.ts
- tests/integration/app_3000_resources/tests.ts
- tests/unit/http/server_test.ts
Fixes #402 
* If the data returned from a method is not of type Response or ResponseOutput, throw an error
> feat: Throw an error if response is not correctly returned from resource

- src/http/request.ts
- tests/unit/http/request_test.ts
@ebebbington, i think the reason you weren't able to test this properly was because you were using `parseBody()` when that method only applies to body params. the `server.getResourceClass()` method is where we assign `request.path_params`. for example, we do this in `server.getResourceClass()`:
```
request.path_params = { "some_param": "some_value" }
```
this happens when the resource is found and before the resource's HTTP method is executed, so that means `request.path_params` is ready to be used inside the resource's HTTP methods.
> feat: getAllPathParams()

- src/http/request.ts
- tests/unit/http/request_test.ts
Addresses #382 
* Adds method to get all header params
* Adds method to get all body params
* Decided against the get all path params, as i can't figure out a solution atm, should we still merge this PR? it only provides 2 out of the 3 methods it was supposed to
> feat: Add getAll methods for header, body and path params

- console/bumper_ci_service_files.ts
- tests/integration/app_3002_https/resources/coffee_resource.ts
- tests/unit/console/bumper_ci_service_test.ts
- tests/unit/core_loggers/file_logger_test.ts
Not sure why the tests were passing for anyone else, but I've sifted through the code and found some areas where they should've failed.
This is especially true for the `file_logger_test.ts` file. It was recreating the `tmp` folder. I already have a `tmp` folder where I do manual testing of the framework. The test would try to make the `tmp` folder and delete the `tmp` folder. It was failing to do so and causing errors.
> chore: fix failing tests

- tests/cli/create_app_test_http.ts
- tests/cli/test_methods.ts
* makes sure `master` is set if `Deno.env.get("GITHUB_HEAD_REF")` returns a falsy value or `""`.
> fix: create app http tests

- .github/workflows/release.yml
Part 1 of 2
* Sends an event to the middleware repo on a release. This will be used by the middleware repo to bump it's dependencies, and hopefully pre-release (part 2)
* Why? We found that to make middleware usable, the drash version it uses has to be the same as the one a user uses, so say a user is using latest of drash (1.4.2), and uses middleare too, but the middleware uses drash v1.4.1, this is incompatible and will throw an error. So with this PR, we're making sure that when drash releases a new version, we release a new middleware version right away that uses the latest of drash
> chore: Notify middleware repo on new drash releases

- src/http/request.ts
- src/http/server.ts
- src/interfaces.ts
- tests/deps.ts
- tests/unit/http/server_test.ts
Started adding tests
Uses es private methods where possible for server because i dont believe a user would need to access any of the methods accept for run
Only expose a single `run` method to the user, where the constructor sets the protocol and the run method determines if to run a http or https server based on that
bye bye sleepy time
> Start constructing tests; use es priv for more server methods

- src/http/response.ts
- src/http/server.ts
- tests/integration/upgrade_websocket_test.ts
POC for `Deno.upgradeWebSocket` usage. For some reason, we can't do this:
```typescript
const { socket, response: res } = Deno.upgradeWebSocket(request);
response.headers = res.headers;
response.status = res.status;
response.statusText = res.statusText;
return response.text("WebSocket connected.");
```
That's why I added the `.upgrade()` method on the `Response`.
Example app:
`import { Drash } from "./deps.ts";` should reference the `mod.ts` in THIS branch.
```typescript
import { Drash } from "./deps.ts";
////////////////////////////////////////////////////////////////////////////////
// FILE MARKER - RESOURCES /////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////
class HomeResource extends Drash.Resource { …
```
> feat: add support for Deno.upgradeWebSocket

- src/http/request.ts
- src/services/graphql/graphql.ts
- tests/deps.ts
- tests/integration/graphql_test.ts
- tests/integration/posting_invalid_json_test.ts
- tests/test_helpers.ts
- tests/unit/http/request_test.ts
* Add check for `Content-Length` header
* If `Content-Length` is null, then there is no body, so return `undefined` for the `#parsed_body`
* If `Content-Length` is 0, then there is no body, so return `undefined` for the `#parsed_body`
* Add check for `Content-Type` header
* If `Content-Length` is greater than 0, then there is a body and we must rely on the `Content-Type` header to parse the body correctly. If it is not present, then we throw a `400 Bad Request` error response.
* Fixed `request_test.ts` tests to include `Content-Length` so that they don't error out. The approach is hacky, but is only used in tests. In the real world, the `Content-Length` header should be provided by the client making the request.
> fix: request content-length and content-type checks

- src/http/response.ts
- src/http/server.ts
- src/services/tengine/tengine.ts
- tests/integration/tengine_test.ts
i tried getting eta to work and it didn't work. also, they're using deno std 0.97.0. i tried getting dejs to work, but its render method returns a `StringReader` object. i think it's going to take more work to integrate other template engines with tengine and i think the implementation would be wonky af. if users want to use another template engine, then they can write their own service to use the template engine
so now we only support jae. might be worth just merging the jae code into the tengine file. we can save that for later though
docs were updated: https://github.com/drashland/website-v2/pull/40
> refactor: tengine

- src/http/error_handler.ts
- tests/unit/http/error_handler_test.ts
Closes #595 
Make sure we default to an HTTP status code of 500 in the event the error object being handled does not contain an HTTP status code that is within the range of HTTP status codes
> fix(http/error_handler): handle errors gracefully

- src/http/request.ts
- src/http/response.ts
- src/types.ts
- tests/unit/http/request_test.ts
- tests/unit/http/response_test.ts
partially addresses #604 
````ts
const file = request.bodyParam<Drash.Types.BodyFile>('profile-picture');
if (!file) {
//
}
console.log(file.content) // Uint8Array [ ... ]
```
Tested by writing the content to a file too, and works fine
> fix: Files from bodyParam are corrupted

- src/http/resource.ts
- src/types.ts
- tests/integration/redirect_test.ts
Closes #607 
* Remove hard-coded 302 in `resource.redirect()` method
* Allow `status` and `headers` to be specified in `resource.redirect()` (just like the response class' methods)
* `status` can only be of type `HttpStatusRedirection` which ranges from 300 - 308 (excluding 306 since it's not a used status)
* We should deprecate the `resource.redirect()` method in favor of `response.redirect()` since `response.redirect()` is the native way to do it based on MDN docs. I didn't know `response.redirect()` existed, so my bad on opting for `resource.redirect()`
> fix: hardcoded redirection http status

- src/http/response.ts
- tests/unit/http/response_test.ts
Closes #611 
According with https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#as_a_response_header_for_the_main_body the value for `Content-Disposition` should contain an equal sign and double quotes for the filename.
> Fix: Content-Disposition value for download method now used correctly

- .gitignore
- deps.ts
- src/http/server.ts
- tests/integration/https_test.ts
- tests/unit/services/cors_test.ts
* Adds `respond(response: Drash.Response) => Response` in request handler so that services can do ...
```typescript
if (endLifecycle) { return respond(response); }
```
... and the request handler and its `catch` block can do ...
```typescript
return respond(response)
```
The `respond(response: Drash.Response) => Response` also includes checking if responses were upgraded in case a service upgrades a response early in the lifecycle.
* Refactored `runServices()` to just return `end`. Reason being, currently in `service-send` branch, if a service throws an error, then we throw that error as soon as possible in the request handler. Instead, we can just not catch the error in `runServices()`, let `runServices()` throw that error to the request handler, then the request handler catches it in …
> refactor: add respond() function to consolidate returning responses in request handler

- .gitignore
- deps.ts
- src/http/server.ts
- tests/integration/https_test.ts
- tests/integration/service_ends_lifecycle_test.ts
- tests/unit/http/request_test.ts
- tests/unit/services/cors_test.ts
> feat: Allow services to end lifecycle

- .gitignore
- src/http/server.ts
- src/interfaces.ts
- src/types.ts
- tests/integration/service_run_at_startup.ts
* Placed types and interfaces to be reused in `interfaces.ts` and `types.ts`
* Added `runAtStartup` to service interface
* Added `Server.addResource()`.
* Refactored server to allow services to run at startup
* Removed `T` prefix from types. I don't know why I started doing this, but they're obviously types because they come from the `types.ts` file. woooooOoOopz.
* Started effort to move our server to expect a service interface as opposed to the `Service` class (kind of like how we're doing it for the error handler -- we expect an interface, not a class)
> feat: Allow services to run at startup

- src/http/server.ts
Closes #636 
Before:
```
Running 10s test @ http://localhost:1447?test=test
2 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   141.61ms  175.94ms   1.97s    95.86%
Req/Sec   424.22     85.40   640.00     73.37%
8498 requests in 10.10s, 4.51MB read
Socket errors: connect 0, read 0, write 0, timeout 11
Non-2xx or 3xx responses: 8498
Requests/sec:    841.39
Transfer/sec:    456.85K
```
After:
```
Running 10s test @ http://localhost:1447
2 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     2.46ms    2.91ms 100.13ms   99.54%
Req/Sec    21.55k     1.24k   22.50k    98.02%
433043 requests in 10.10s, 56.58MB read
Requests/sec:  42867.70
Transfer/sec:      5.60MB
```
> perf: don't find resource if already matched to previous request URL

- src/http/server.ts
Closes #635
Before:
```
Running 5s test @ http://localhost:1447?test=test
2 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency   162.52ms  253.89ms   1.99s    92.58%
Req/Sec   473.68     72.50   643.00     73.00%
4796 requests in 5.09s, 2.54MB read
Non-2xx or 3xx responses: 4796
Requests/sec:    941.74
Transfer/sec:    511.34KB
```
After:
```
Running 5s test @ http://localhost:1447?test=test
2 threads and 100 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency     3.74ms    5.18ms 124.77ms   99.08%
Req/Sec    14.80k     1.48k   15.78k    90.20%
150207 requests in 5.10s, 19.63MB read
Requests/sec:  29431.85
Transfer/sec:      3.85MB
```
> fix: check for non-empty accept header before performing accept header flow

- src/http/request.ts
- tests/unit/http/request_test.ts
> fix: ensure consistent falsy return values for body params

- src/services/graphql/deps.ts
- src/services/graphql/graphql.ts
- src/services/graphql/graphql_resource.ts
- tests/integration/graphql_test.ts
Closes #646 
- PR: https://github.com/drashland/website-v2/pull/170
- Page: https://drash-land-git-feat-graphql-improved-docs-drash-land.vercel.app/drash/v2.x/tutorials/services/drash-approved-services/graphql
* refactor: `GraphQLService` creates the GraphQL playground resource at startup time
* feat: add option `playground_path` to allow user to define different GraphQL playground endpoint
* test: updates `GraphQLService` test
```typescript
// app.ts
import { Drash, GraphQL, GraphQLService } from "./deps.ts";
// Set up your GraphQL environment
const schema = GraphQL.buildSchema(`
type Query {
greeting: String
}
`);
const root = {
greeting: () => { // or greeting: (source, args, context, info) => {
return "Hello world!";
},
};
// Instantiate the GraphQL service
const graphQl = new …
```
> feat: remove GraphQL service empty resource requirement; add option to change playground endpoint

- src/http/request.ts
- src/http/server.ts
- src/interfaces.ts
- src/types.ts
- tests/integration/server_with_optionals_request_test.ts
Closes #669 
Adds an `optionals` server config that takes in a `request` optionals object. We can use this `optionals` config to introduce changes to different HTTP objects if needed.
Example:
```typescript
import * as Drash from "/path/to/drash/mod.ts";
class HomeResource extends Drash.Resource {
public paths = [
"/",
];
public async POST(
request: Drash.Request,
response: Drash.Response,
): Promise<void> {
// Since the body was not read, users can call the request methods themselves
const body = await request.blob();
console.log(body); // Example output => Blob { size: 15, type: "image/png" }
response.text("Hello");
}
}
const server = new Drash.Server({
hostname: "0.0.0.0",
port: 1447,
protocol: "http",
resources: [
HomeResource,
],
optionals: {
request: {
read_body: false, // Prevents …
```
> feat(http/server): add request optionals to control reading the body

- src/services/resource_loader/deps.ts
Bump `ResourceLoaderService` to Deno Standard Modules 0.158.0
> chore: Bump ResourceLoaderService to Deno Standard Modules 0.158.0

- src/http/request.ts
- tests/integration/post_no_body_test.ts
- tests/integration/server_with_optionals_request_test.ts
- tests/unit/http/request_test.ts
@ebebbington, this approach passes in a request clone to `super()` in `DrashRequest`'s constructor. most of the current code is left intact, the old tests are being used, and there are also tests i added in addition to the tests you added.
when i reviewed your PR, i noticed we couldn't get the `request.original` without the code throwing `Illegal invocation` which means we'd break current functionality because we allow users to access `request.original`. see screenshot below:
i think the approach in this PR is the one we should go with. thoughts @ebebbington @Guergeiro? i could def be missing something here. this deno change seems like it had a big impact and we might just be hitting the surface with its effects.
> fix: sending a POST request without a body
